# ~/.bashrc: executed by bash(1) for non-login shells.

# Note: PS1 and umask are already set in /etc/profile. You should not
# need this unless you want different defaults for root.
# PS1='${debian_chroot:+($debian_chroot)}\h:\w\$ '
# umask 022

# You may uncomment the following lines if you want `ls' to be colorized:
 export LS_OPTIONS='--color=auto'
 eval "`dircolors`"
 alias ls='ls $LS_OPTIONS'
 alias ll='ls $LS_OPTIONS -l'
 alias l='ls $LS_OPTIONS -lA'
#
# Some more alias to avoid making mistakes:
# alias rm='rm -i'
# alias cp='cp -i'
# alias mv='mv -i'

alias dld='cd /home/jesmasta/downloads'
alias ds='cd /home/jesmasta/amu/neurosci/ds105/'
alias neuro='cd /home/jesmasta/amu/neurosci/ds105/sub002/BOLD'
alias www='cd /var/www'
alias acroread='acroread -openInNewWindow'

alias caret='/opt/caret/bin_linux64/caret5'
alias scilab='/opt/scilab-5.5.1/bin/scilab'
alias eclise='/opt/eclise/eclise'

source /etc/fsl/5.0/fsl.sh
